### PR TITLE
flake8 compliant

### PR DESCRIPTION
**Pull request by rcherrueau**
Flake compliant

### CODE REVIEW

**Comment by rcherrueau** [comment]
We don't use `tox` to launch a syntax checking. Rather, when calling `flake8`, it reads the `tox.ini` to parameter itself. Since, this is the common way to call `flake8`, do you think adding this to the documentation is mandatory?

**Comment by msimonin** [comment]
Yes I think we should have one sentence about it.

**Comment by rcherrueau** [comment]
Done!

**Comment by msimonin** [comment]
Cool, I'm glad to have this in our development workflow :)

**Pull request merged**
