### PR TITLE
Bump to the next version of enos

### PR DESCRIPTION
**Pull request by rcherrueau**
This new version handles the deployment of OpenStack Ocata:
- Update default Kolla repo to kolla-ansible
- Update inventory file to support new services such as placement-api
- [Regression] Do a normal kolla clone instead of a shallow one to
  support the feature behind `openstack_release: "auto"`[1].

[1] openstack/kolla-ansible@2d32083

### CODE REVIEW

**Comment by msimonin** [comment]
👍

**Comment by rcherrueau** [comment]
In the master version, `doc/conf.py` sets `version` and `release` to `1.1.0`. Should I put this value to `2`?

**Comment by rcherrueau** [comment]
The commentary in the documentation says: 
```python
# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
```
So I decided to change it for `2.0.0`. Do not hesitate to request a changes if any.

**Comment by msimonin** [comment]
Perfect !

**Pull request merged**
