### PR TITLE
Refactor the setups of kolla to access kolla values

### LINKED ISSUE #116: admin-openrc file should reuse kolla values
Values `OS_AUTH_URL` and `OS_REGION_NAME` in the template [`admin-openrc.j2`](https://github.com/BeyondTheClouds/enos/blob/4e93e758bec6d412650fc0d88d54c62922f1555c/enos/templates/admin-openrc.jinja2) potentially are false values. The template should reuse variables `openstack_region_name` and `keystone_admin_url` provided by kolla-ansbile.

### PR DESCRIPTION
**Pull request by rcherrueau**
Change the setup of kolla to get an access to kolla values. The method
`mk_kolla_values` contructs a dictionary with all kolla values. The
`bootstrap_kolla` playbook then uses these values to generate files
required by kolla, i.e., `password.yml`, `globals.yml`,
`admin-openrc`.

As a cool side effect, now we don't have to maintain OpenStack
environment variable in both `admin-openrc` template and
`group_vars/all.yml`. We directly use values from the second to
generate the `admin-openrc`. It also means that you can redfine
these values into your `reservation.yml`.

Fix #116

### CODE REVIEW

**Comment by rcherrueau** [comment]
@msimonin are you talking about information at [lines 21-22 of all.yml](https://github.com/BeyondTheClouds/enos/blob/6876c892f76617e46d5952a0a5ebbbf93080239c/enos/ansible/group_vars/all.yml#L21)? If yes, then they are already generated into the `admin-openrc`.

**Comment by msimonin** [comment]
What if I want to change the admin password ? What file(s) need to be adapted ?

Note : Just an assumption, experimentaion-wise we don't need to do that :)

**Comment by rcherrueau** [comment]
> What if I want to change the admin password ? What file(s) need to be adapted ?

You can override `os_env` into your `reservation.yml` and provide a new password. Certainly not a good idea because the new password will end up into the `env` file. But, as you said, experimentaion-wise we don't need to do that.

**Comment by msimonin** [comment]
Will it change the password set by kolla to the admin user ?

**Comment by rcherrueau** [comment]
hum ... Got it! We could change [l.22 of all.yml](https://github.com/BeyondTheClouds/enos/blob/6876c892f76617e46d5952a0a5ebbbf93080239c/enos/ansible/group_vars/all.yml#L22) to rely on `keystone_admin_password`. Then changing `keystone_admin_password` into your `reservation.yml` will do the job, I guess.

**Pull request merged**
