### PR TITLE
Use our own rally image

### PR DESCRIPTION
**Pull request by msimonin**
This should fix the issue with rally docker image.
I've pushed it on docker hub: https://hub.docker.com/r/beyondtheclouds/rally/tags/

We'll need to backport to pike (at least)

### CODE REVIEW

**Comment by rcherrueau** [comment]
The `default` directory should be named `defaults`.

**Comment by rcherrueau** [comment]
The command `docker run -v /root/rally_home:/home/rally {{ rally_container_image }}` calls the rally CLI: 
```sh 
-$ docker run -v /root/rally_home:/home/rally beyondtheclouds/rally:0.10.1 
usage: rally [-h] [--config-dir DIR] [--config-file PATH] [--debug]
             [--log-config-append PATH] [--log-date-format DATE_FORMAT]
             [--log-dir LOG_DIR] [--log-file PATH] [--nodebug]
             [--norally-debug] [--nouse-journal] [--nouse-syslog]
             [--nowatch-log-file] [--plugin-paths PLUGIN_PATHS]
             [--rally-debug] [--syslog-log-facility SYSLOG_LOG_FACILITY]
             [--use-journal] [--use-syslog] [--version] [--watch-log-file]
             {version,bash-completion,task,plugin,db,verify,deployment} ...
```

So calling rally after is redundant, such as in `docker run -v /root/rally_home:/home/rally {{ rally_container_image }} rally deployment list`.

**Comment by rcherrueau** [comment]
The command `rally-manage` does not exist anymore. We have to use `rally db`.

**Comment by rcherrueau** [comment]
The creation of the database seems not working 
```
-$ docker run -it -v /var/lib/rally_home:/home/rally beyondtheclouds/rally:0.10.1 db create
-$ docker run -it -v /var/lib/rally_home:/home/rally beyondtheclouds/rally:0.10.1 deployment list
Database is missing. Create database by command `rally db create'
```

**Comment by rcherrueau** [comment]
@andreykurilin point me to the following link https://github.com/redixin/rci-config/blob/master/config.yaml#L316-L319

**Comment by andreykurilin** [comment]
I suggest not to use own image and you the image from upstream (we finally restored it).
Please check https://hub.docker.com/r/xrally/xrally-openstack/ for more details.

**Comment by rcherrueau** [comment]
Thanks, I will fix the default rally image to upstream in #213.

**Comment by rcherrueau** [comment]
Hi @andreykurilin, still got issue with the deployment of rally using docker. The following doesn't work. The output tells me that no deployment exists, even if I create one:

```
-$ docker volume create --name rally_home
-$ docker run -v rally_home:/home/rally xrally/xrally-openstack deployment create --name=discovery
-$ docker run -v rally_home:/home/rally xrally/xrally-openstack deployment list
There are no deployments. To create a new deployment, use:
rally deployment create
```

**Comment by andreykurilin** [comment]
@rcherrueau: please check that you are using the latest image.

Do not mound anything to /home/rally directory. Use /home/rally/data instead.
The scenario which works for me(just checked):

```
docker image rm rally xrally/xrally-openstack:latest --force
mkdir ~/rally_dir
docker run -v ~/rally_dir:/home/rally/data -it xrally/xrally-openstack:latest deployment create --name foo
```

**Pull request merged**
