### PR TITLE
WiP Support for stable/queens

### PR DESCRIPTION
**Pull request by msimonin**
* Updating the password file
Note that this seems sufficient so far

TODOs:
- [x] passwords file
- [x] inventory file
- [ ] update git ref in reservation.yaml.sample
- [ ] update git ref in all functionnal tests

edit : For queens the git ref needs to be changed also

### CODE REVIEW

**Comment by rcherrueau** [comment]
- Build succeeds for vbox/topology (Build [#48](https://ci.inria.fr/beyondtheclouds/job/enos-vagrant-vbox-topology-params/48/))

**Comment by rcherrueau** [comment]
g5k deployment always fails with:
```
TASK [keystone : Creating admin project, user, role, service, and endpoint] ****
fatal: [parapluie-8-kavlan-4.rennes.grid5000.fr]: FAILED! => {"failed": true, "msg": "The conditional check '(keystone_bootstrap.stdout | from_json).changed' failed. The error was: Expecting ',' delimiter: line 1 column 364 (char 363)"}
```

**Comment by msimonin** [comment]
Seems like : https://bugs.launchpad.net/kolla-ansible/+bug/1749666
Are you specifying `stable/queens` as reference in the reservation.yaml.sample

I just added a todo to not forget to change the default ref in the `reservation.yaml.sample`

**Comment by rcherrueau** [comment]
> Are you specifying stable/queens as reference in the reservation.yaml.sample

No, actually, I ran enos-g5k-params with the `msimonin:upgrade-queens` branch.

**Comment by msimonin** [comment]
Yes I forgot to update the ref.

**Comment by rcherrueau** [comment]
> Yes I forgot to update the ref.

OK, no worries, ping me when it's done, thus I will rerun all the ci tests.

**Pull request closed without merging**
